CREATE DATABASE olist_ecommerce;
USE olist_ecommerce;

CREATE TABLE customers (
    customer_id VARCHAR(50),
    customer_unique_id VARCHAR(50),
    customer_zip_code_prefix INT,
    customer_city VARCHAR(50),
    customer_state VARCHAR(10)
);
SELECT * FROM customers;

CREATE TABLE orders (
    order_id VARCHAR(50),
    customer_id VARCHAR(50),
    order_status VARCHAR(30),
    
    order_purchase_timestamp DATETIME,
    order_approved_at DATETIME,
    order_delivered_carrier_date DATETIME,
    order_delivered_customer_date DATETIME,
    order_estimated_delivery_date DATETIME
);
SELECT * FROM orders;

CREATE TABLE order_items (
    order_id VARCHAR(50),
    order_item_id INT,
    product_id VARCHAR(50),
    seller_id VARCHAR(50),
    shipping_limit_date DATETIME,
    price DECIMAL(10,2),
    freight_value DECIMAL(10,2)
);
SELECT * FROM order_items;

CREATE TABLE payments (
    order_id VARCHAR(50),
    payment_sequential INT,
    payment_type VARCHAR(30),
    payment_installments INT,
    payment_value DECIMAL(10,2)
);
SELECT * FROM payments;

-- LEVEL 1 BEGINNER
-- Q1. How many orders are present in the dataset?
SELECT COUNT(*) AS total_orders
FROM orders;

-- Q2. What is the distribution of orders by order_status?
SELECT 
    order_status,
    COUNT(*) AS order_count
FROM orders
GROUP BY order_status
ORDER BY order_count DESC;

-- Q3. What is the total revenue generated by the platform?
SELECT 
	SUM(price) AS total_revenue
FROM order_items;

-- How many unique customers have placed at least one order?
SELECT 
    COUNT(DISTINCT customer_id) AS active_customers
FROM orders;

-- LEVEL 2 INTERMEDIATE
-- Q4. How much revenue comes from each order_status?
SELECT 
    o.order_status,
    SUM(oi.price) AS revenue
FROM orders o
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.order_status
ORDER BY revenue DESC;

-- Q5. How many customers have placed more than one order?
SELECT COUNT(*) AS repeat_customers
FROM (
    SELECT customer_id
    FROM orders
    GROUP BY customer_id
    HAVING COUNT(order_id) > 1
) AS repeat_customer_list;

-- LEVEL-3 ADVANCED
-- Q6. What percentage of total revenue is generated by the top 10% of customers?   
WITH revenue_per_customer AS (
    SELECT 
        o.customer_id,
        SUM(oi.price) AS customer_revenue
    FROM orders o
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.customer_id
),
ranked_customers AS (
    SELECT
        customer_id,
        customer_revenue,
        NTILE(10) OVER (
            ORDER BY customer_revenue DESC, customer_id
        ) AS revenue_decile
    FROM revenue_per_customer
),
top_customers AS (
    SELECT 
        SUM(customer_revenue) AS top_customers_revenue
    FROM ranked_customers
    WHERE revenue_decile = 1
),
total_rev AS (
    SELECT SUM(price) AS total_revenue
    FROM order_items
)
SELECT 
    (top_customers_revenue / total_revenue) * 100 AS percentage_revenue_top_10_percent
FROM top_customers, total_rev;


-- Q7. What percentage of customers placed more than one order?
WITH orders_per_customer as (
	SELECT customer_id,
			COUNT(*) as order_count
	FROM orders
    GROUP BY customer_id
),
repeat_customers as (
	SELECT COUNT(customer_id) AS repeat_customer_count
    FROM orders_per_customer
    WHERE order_count > 1
),
total_customers as (
	SELECT COUNT(customer_id) as total_customers_count
    FROM orders_per_customer
)

SELECT 
	(repeat_customer_count / total_customers_count) * 100.0 as customer_repeat_rate
FROM repeat_customers, total_customers;

-- VERIFYING 0% CUSTOMER REPEAT RATE 
-- Inspect the raw counts
WITH orders_per_customer AS (
    SELECT 
        customer_id,
        COUNT(*) AS order_count
    FROM orders
    GROUP BY customer_id
)
SELECT 
    MIN(order_count) AS min_orders,
    MAX(order_count) AS max_orders
FROM orders_per_customer;

-- Check if ANY customer has more than 1 order
WITH orders_per_customer AS (
    SELECT 
        customer_id,
        COUNT(*) AS order_count
    FROM orders
    GROUP BY customer_id
)
SELECT *
FROM orders_per_customer
WHERE order_count > 1
LIMIT 10;

-- Verify repeat customer count explicitly
WITH orders_per_customer AS (
    SELECT 
        customer_id,
        COUNT(*) AS order_count
    FROM orders
    GROUP BY customer_id
)
SELECT COUNT(*) AS repeat_customers_count
FROM orders_per_customer
WHERE order_count > 1;

-- Q8. How does customer retention change over time based on when customers first purchased?
WITH order_month as (
	SELECT 	
		order_id,
		customer_id, 
		date_format(order_purchase_timestamp, '%Y-%m-01') as order_month
	FROM orders),
    
cohort_month as(
	SELECT 
		customer_id,
		MIN(order_month) as cohort_month
	FROM order_month
    GROUP BY customer_id
),

cohort_index as (
	SELECT 
		o.customer_id, 
		c.cohort_month, 
		o.order_month,
		TIMESTAMPDIFF(MONTH, c.cohort_month, o.order_month) AS cohort_index
	FROM order_month AS o
	LEFT JOIN cohort_month AS c
		ON o.customer_id = c.customer_id
),

cohort_table as (
	SELECT 
		cohort_month,
        cohort_index,
        COUNT(DISTINCT customer_id) AS customers
	FROM cohort_index
    GROUP BY cohort_month, cohort_index
)

SELECT *
FROM cohort_table
ORDER BY cohort_month, cohort_index;

-- Q9. What percentage of total revenue is actually realized (delivered orders)?
WITH revenue_delivered AS (
    SELECT 
        SUM(oi.price) AS revenue_delivered
    FROM orders o
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
),
total_revenue AS (
    SELECT 
        SUM(price) AS total_revenue
    FROM order_items
)

SELECT 
    (revenue_delivered * 100.0 / total_revenue) AS realized_revenue_percentage
FROM revenue_delivered, total_revenue;
